import type { Metadata } from "next";

import "./globals.css";


import localFont from "next/font/local"



const myCustomFont = localFont({
  src: './fonts/SF-Pro-Display-Black.woff', // Path to your font file
  variable: '--font-custom', // Define a CSS variable
  display: 'swap',
});

const myCustomFontSecond = localFont({
  src: './fonts/SF-Pro-Display-Medium.woff', // Path to your font file
  variable: '--font-customsecond', // Define a CSS variable
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Aashish Raja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myCustomFont.variable} ${myCustomFontSecond.variable} antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
